config/routes.rb
RankChecker::Application.routes.draw do
  
  resources :ranks

  root :to => "rank_checker#index"
  resources :users
  
  match "rank-checker" => "rank_checker#index"
  match "rank-checker/api/" => "rank_checker#api"
  match "rank-checker/:id" => "rank_checker#show"
  match "sessions/new" => "sessions#new"
  match "sessions/create" => "sessions#create"
  match "sessions/logout" => "sessions#destroy"
  

end

app/models/rank.rb
class Rank < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ranks
  attr_accessible :email, :password, :password_confirmation
  
  has_secure_password

  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :email
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
  private
    
    ##
    # returns the +current_user+'s object using the +user_id+ stored in +session[:user+id]+
    #
    # ==== Returns
    # +user+ object
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    
    
    def logged_in
      
      if(session[:user_id] != nil)
        return true
      end
      
      flash[:warning] = "Please login to continue"
      # session[:return_to] = request.request_uri
      redirect_to sessions_new_path
      return false
      
    end
  
  helper_method :current_user, :logged_in
  
end

app/controllers/rank_checker_controller.rb
require "fetcher-socket"
class RankCheckerController < ApplicationController
  def index
    rip = request.remote_ip
    rip = rip.to_s.gsub /\./, ""
    user_id = session[:user_id] != nil ? session[:user_id] : 0
    params["thread_str"] = "#{rip}-#{Time.now.to_i}"+"-"+ params["thread_str"] + "-#{user_id}"
    FetcherSocket::get_rank params["thread_str"], params[:domain], params[:keyword]
    params[:rank] = "0"
    respond_to do |format|
      format.html
      format.json {render :json => params.to_json}
    end
  end
  
  def show
    json_str = FetcherSocket::get_progress params["id"]
    json_str = json_str.chomp if json_str != nil
    respond_to do |format|
      format.html
      format.json {render :json => json_str.to_json}
    end
  end
  
  def api
    r = Checker.new
    r.domain = params[:domain]
    rank = r.find_rank_for_keyword params[:keyword]
    respond_to do |format|
      format.html
      format.json {render :json => r.to_json}
    end
  end
end

app/controllers/ranks_controller.rb
require 'checker.rb'
class RanksController < ApplicationController
  before_filter :logged_in
  # http_basic_authenticate_with :name => "apoorv", :password => "thering"
  # GET /ranks
  # GET /ranks.json
  
  
  def index
    @user = User.find(session[:user_id])
    @ranks = @user.ranks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ranks }
    end
  end

  # GET /ranks/1
  # GET /ranks/1.json
  def show
    @rank = Rank.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rank }
    end
  end

  # GET /ranks/new
  # GET /ranks/new.json
  def new
    @rank = Rank.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rank }
    end
  end

  # GET /ranks/1/edit
  def edit
    @rank = Rank.find(params[:id])
  end

  # POST /ranks
  # POST /ranks.json
  def create
    @rank = Rank.new(params[:rank])
    respond_to do |format|
      if @rank.save
        format.html { redirect_to @rank, notice: 'Rank was successfully created.' }
        format.json { render json: @rank, status: :created, location: @rank }
      else
        format.html { render action: "new" }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ranks/1
  # PUT /ranks/1.json
  def update
    @rank = Rank.find(params[:id])

    respond_to do |format|
      if @rank.update_attributes(params[:rank])
        format.html { redirect_to @rank, notice: 'Rank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranks/1
  # DELETE /ranks/1.json
  def destroy
    @rank = Rank.find(params[:id])
    @rank.destroy

    respond_to do |format|
      format.html { redirect_to ranks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  before_filter :logged_in, :only => ['index']
  
  def show
  
  end
  
  def new
    if (current_user)
      redirect_url = request.env["HTTP_REFERER"] != nil ? request.env["HTTP_REFERER"] : ranks_path
      redirect_to redirect_url
    end
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to ranks_path, :noitce => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      redirect_to new_user_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to sessions_new_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to ranks_path
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rank_checker_helper.rb
module RankCheckerHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RankChecker</title>
  <%= stylesheet_link_tag "bootstrap-combined.min.css"%>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:jshead) %>
</head>
<body>

<div class="wrapper">
	<div class="right-section">
		<div class="right-content" style="width:38%">
			
			<div id="rank-details">
				
			</div>
			
		</div>
	</div>
	
	<div class="left-section">
		<div class="header">
			<div class="logo">
				<h1>
					<span>&nbsp;rank</span><br/>
					<span>checker</span>
				</h1>
			</div>
		</div>
		<%= yield %>
	</div>

</div>

</body>
</html>

app/views/rank_checker/index.html.erb
<%= @domain %>

app/views/ranks/_form.html.erb
<%= form_for(@rank) do |f| %>
  <% if @rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank.errors.count, "error") %> prohibited this rank from being saved:</h2>

      <ul>
      <% @rank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_area :keyword %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.number_field :page %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ranks/edit.html.erb
<h1>Editing rank</h1>

<%= render 'form' %>

<%= link_to 'Show', @rank %> |
<%= link_to 'Back', ranks_path %>

app/views/ranks/index.html.erb
<%content_for(:head) do %>
	<%= javascript_include_tag "jquery.animate-color.js" %>
<%end%>


<% content_for(:domain_details) do%>
	
<%end%>

<script type="text/html" id="details-template">
	<div class="details" id="details-progress-{{=progress_id}}">
		<span class="pane-domain">
			<h1>{{= domain }}</h1>
		</span>
		<span class="pane-keyword">
			{{= keyword }}
		</span>
		<div class="progress-holder" id="details-update-{{=progress_id}}">
			<div class="progress progress-striped" style="height:4px;">
				<div class="bar" style="width:100%;background-color:#558899">
				</div>
			</div>
			<div class="message">{{=message}}</div>
		</div><br />
		<div class="pane-el pane-rank">
		
		</div>
		<div class="pane-el pane-page">
		
		</div>
		<span class="pane-el pane-path">
		</span><br />
		<span class="pane-el pane-link">
			<a href="{{=url}}" target="_blank">{{=url}}</a>
		</span>
	</div>
</script>

<div id="ranklist-app">
	<form id="new_rank">
		<input type="text" class="tracker-input" name="rank[domain]" value="facebook.com"/>
		<input type="text" class="tracker-input" name="rank[keyword]" value="apoorv parijat"/> 
		<input class="go-arrow" type="image" height="40" src="/assets/go.png">
	</form>
	<br/><br/>
	<table id="ranks">
		<thead>
			<tr class="table-header">
				<td style="min-width:150px">
					&nbsp;
				</td>
				<td style="min-width:200px">
					&nbsp;
				</td>
				<td style="min-width:50px">
					&nbsp;
				</td>
				<td>
					&nbsp;&nbsp;
				</td>
			</tr>
		</thead>
	</table>
</div>



<script type="text/javascript">
	$(function(){
		RankList.init();
	});
</script>

app/views/ranks/new.html.erb
<h1>New rank</h1>

<%= render 'form' %>

<%= link_to 'Back', ranks_path %>

app/views/ranks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Domain:</b>
  <%= @rank.domain %>
</p>

<p>
  <b>Keyword:</b>
  <%= @rank.keyword %>
</p>

<p>
  <b>Page:</b>
  <%= @rank.page %>
</p>

<p>
  <b>Position:</b>
  <%= @rank.position %>
</p>

<p>
  <b>Rank:</b>
  <%= @rank.rank %>
</p>

<p>
  <b>Ip:</b>
  <%= @rank.ip %>
</p>


<%= link_to 'Edit', edit_rank_path(@rank) %> |
<%= link_to 'Back', ranks_path %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">	
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>